In [2]:
import pandas as pd
import numpy as np

In [3]:
data: list[list[str | int | None]]= [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns: list[str] = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [6]:
df.Model

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: str

In [12]:
df['id'] = ['nis1', 'hyu1', 'lot2', 'gmc1', 'nis2']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [13]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP', 'id'],
      dtype='str')

In [14]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
id                     nis1
Name: 0, dtype: object

In [15]:
df.iloc[[1, 3, 0]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1

In [16]:
n_train = 3
n_val = 1
n_test = 1

In [17]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [18]:
df.iloc[:2]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1

In [19]:
df.iloc[1:3]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2

Element wise opperations

In [22]:
df['Engine Cylinders'] * 2

0     8
1     8
2     8
3     8
4    12
Name: Engine Cylinders, dtype: int64

In [23]:
df['Year'] > 2000

0    False
1     True
2     True
3     True
4     True
Name: Year, dtype: bool

In [24]:
df[df['Year']>2000]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [25]:
df[(df['Year'] > 2010) & (df['Transmission Type'] == 'AUTOMATIC')]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1

String operations

In [26]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [28]:
df['Vehicle_Style'].str.capitalize()

0          Sedan
1          Sedan
2    Convertible
3        4dr suv
4         Pickup
Name: Vehicle_Style, dtype: str

In [32]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [34]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [35]:
df.dtypes

make                     str
model                    str
year                   int64
engine_hp            float64
engine_cylinders       int64
transmission_type        str
vehicle_style            str
msrp                   int64
id                       str
dtype: object

In [36]:
df.dtypes.index

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp', 'id'],
      dtype='str')

Summarizing operations (EDA)

In [38]:
df['msrp'].mean()

np.float64(30186.0)

In [39]:
df['msrp'].sum()

np.int64(150930)

In [40]:
df['msrp'].min()

np.int64(2000)

In [41]:
df['msrp'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: msrp, dtype: float64

In [ ]:
df['make'].nunique()

4

In [45]:
df['make'].unique().tolist()

['Nissan', 'Hyundai', 'Lotus', 'GMC']

In [46]:
df['make'].value_counts()

make
Nissan     2
Hyundai    1
Lotus      1
GMC        1
Name: count, dtype: int64

In [47]:
df.isnull()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp,id
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [49]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            1
engine_cylinders     0
transmission_type    0
vehicle_style        0
msrp                 0
id                   0
dtype: int64

In [50]:
df['engine_hp'].fillna(df['engine_hp'].mean())

0    138.00
1    202.75
2    218.00
3    194.00
4    261.00
Name: engine_hp, dtype: float64

In [51]:
df['engine_hp'] = df['engine_hp'].fillna(df['engine_hp'].mean())

In [52]:
df.sort_values(by='msrp', ascending=False)

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp,id
2,Lotus,Elise,2010,218.00,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.00,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.00,6,MANUAL,Pickup,32340,nis2
1,Hyundai,Sonata,2017,202.75,4,AUTOMATIC,Sedan,27150,hyu1
0,Nissan,Stanza,1991,138.00,4,MANUAL,sedan,2000,nis1

Grouping

In [53]:
df.groupby('transmission_type')['msrp'].mean()

transmission_type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: msrp, dtype: float64

In [54]:
df.groupby('transmission_type')['msrp'].agg(['mean', 'count'])

                           mean  count
transmission_type
AUTOMATIC          30800.000000      2
MANUAL             29776.666667      3

In [57]:
u = np.array([2, 3, 4, 5])
u.shape[0]

4